In [3]:
import numpy as np

#### 1) one dimensional array a1 contain 5 numercal value

In [67]:
a01=[1,2,3,4,5.5,8,9,7,6,85]
a1=np.array(a01)
print(a1)

[ 1.   2.   3.   4.   5.5  8.   9.   7.   6.  85. ]


#### 2) two dimensional array a2 with three rows and five column containing any numerical value


In [11]:
r1=[4.5,57,8,98,54.4]
r2=[8,9,8.3,87,9]
r3=[87,96,53.7,8,5]
a2=np.array([r1,r2,r3])
print(a2)

[[ 4.5 57.   8.  98.  54.4]
 [ 8.   9.   8.3 87.   9. ]
 [87.  96.  53.7  8.   5. ]]


##### 3) one dimensional arrat a3 containig name of 5 cities of maharashtra


In [13]:
c=['mumbai','raigad','dhule','nanded','alibag']
a3=np.array(c)
print(a3)

['mumbai' 'raigad' 'dhule' 'nanded' 'alibag']


#### 4) two dimensional array a4containing with first column name of state and capital of that state of india

In [53]:
stats=['maharastra','Andhra Pradesh','Arunachal Pradesh']
capital=['mumbai','Amaravati','Itanagar']
a4=np.array([stats,capital])
a45=a4.T
print(a45)

[['maharastra' 'mumbai']
 ['Andhra Pradesh' 'Amaravati']
 ['Arunachal Pradesh' 'Itanagar']]


#### 5) display size shape dimension datatype of each of the array created

In [26]:
#for a1
print(a1.size)
print(a1.shape)
print(a1.ndim)
print(a1.dtype)

5
(5,)
1
float64


In [27]:
#for a2
print(a2.size)
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

15
(3, 5)
2
float64


In [28]:
#for a3
print(a3.size)
print(a3.shape)
print(a3.ndim)
print(a3.dtype)

5
(5,)
1
<U6


In [30]:
#for a4
print(a4.size)
print(a4.shape)
print(a4.ndim)
print(a4.dtype)

6
(2, 3)
2
<U17


#### 6) display all the arrays in the reverse order

In [34]:
print(a1[::-1])#for a1
print(a2[::-1])#for a2
print(a3[::-1])#for a3
print(a4[::-1])#for a4

[5.5 4.  3.  2.  1. ]
[[87.  96.  53.7  8.   5. ]
 [ 8.   9.   8.3 87.   9. ]
 [ 4.5 57.   8.  98.  54.4]]
['alibag' 'nanded' 'dhule' 'raigad' 'mumbai']
[['mumbai' 'Amaravati' 'Itanagar']
 ['maharastra' 'Andhra Pradesh' 'Arunachal Pradesh']]


#### 7) display 1,2,-2,-1 element of one dimensional array

In [36]:
ar=[1,2,-2,-1]
print(np.array(ar))

[ 1  2 -2 -1]


#### 8) display second row and third row and all column of all two dimensional array created above

In [51]:
print(a2[1:])

[[ 8.   9.   8.3 87.   9. ]
 [87.  96.  53.7  8.   5. ]]


In [54]:
print(a45[1:])

[['Andhra Pradesh' 'Amaravati']
 ['Arunachal Pradesh' 'Itanagar']]


#### 1)create an array of size 10 starting with 3 and next number increase by 2 using arange method

In [60]:
ar1=np.arange(3,22,2)
print(ar1)

[ 3  5  7  9 11 13 15 17 19 21]


#### 2)create an array of dimensional (2,5) and (5,2) using the array created above


In [71]:
av2=a1.reshape(2,5)
av2

array([[ 1. ,  2. ,  3. ,  4. ,  5.5],
       [ 8. ,  9. ,  7. ,  6. , 85. ]])